### ISSUE TITLE
Failed adding vault: Shared Google Drive vault

### ISSUE THREAD

**Issue by Phil-ipp1** [buttercup/buttercup-desktop#1200]
Hello,
I tried to open a Buttercup vault which is stored on a shared Google Drive. 
It seems that a direct access to shared drives/files is not possible so I added a shortcut to my personal Drive.
I get the following error:
Failed adding vault: Failed unlocking source: Failed fetching Google Drive Vault: Request Failed Request failed: 403 Forbidden.

![Capture](https://user-images.githubusercontent.com/128125615/231740889-c79c26c4-f111-4cfd-9487-3d9dece1d939.PNG)
Vaults that are stored directly on my personal drive work like a charm.

Is there any possiblity to open vaults on shared drives or to open shared vaults?

**Comment by perry-mitchell** [comment]
Just to let you know I haven't forgotten this. Unfortunately I've had to make far larger changes than I'd hoped, in the effort to get this working. `2.19.0` will be out tomorrow hopefully if everything is stable.

**Comment by perry-mitchell** [comment]
@Phil-ipp1 I've released 2.19.. can you please check again?

**Comment by perry-mitchell** [comment]
Working on this! ETA some time this evening. Currently blocked by npm having an outage:
![image](https://user-images.githubusercontent.com/3869469/234075242-93926791-29c5-4f47-b45f-df65bbc8560b.png)

**Comment by perry-mitchell** [comment]
Will be released in 2.19.1.

**Comment by tigrouind** [comment]
@perry-mitchell 2.19.1 fixes the issue that prevents adding a vault located on Google Drive. 

However, the syncing is still broken. After doing changes to a vault (eg: creating or updating a password) the vault is not updated, instead a "Untitled" file is created in same folder as the vault and it contains '[object Object]'. In Buttercup, everything looks fine : a progress bar is created and no errors are reported (in other words, it fails silently).
